import { defineConfig } from "vitest/config";
import path from "path";

export default defineConfig({
  test: {
    environment: "node",
    include: [
      "packages/fetchers/nominatim/src/**/*.test.ts",
      "packages/fetchers/bhulekh/src/**/*.test.ts",
      "packages/fetchers/bhunaksha/src/**/*.test.ts",
      "packages/fetchers/ecourts/src/**/*.test.ts",
      "packages/fetchers/high-court/src/**/*.test.ts",
      "packages/fetchers/drt/src/**/*.test.ts",
      "packages/fetchers/rccms/src/**/*.test.ts",
      "packages/fetchers/igr-ec/src/**/*.test.ts",
      "packages/fetchers/cersai/src/**/*.test.ts",
      "packages/fetchers/rera/src/**/*.test.ts",
      "packages/fetchers/larr/src/**/*.test.ts",
      "packages/schema/src/**/*.test.ts",
      "packages/orchestrator/src/**/*.test.ts",
      "agents/ownership-reasoner/**/*.test.ts",
      "agents/encumbrance-reasoner/**/*.test.ts",
      "agents/consumer-report-writer/src/**/*.test.ts",
      "agents/output-auditor/src/**/*.test.ts",
      "agents/land-classifier/**/*.test.ts",
      "packages/pdf-renderer/src/**/*.test.ts",
    ],
  },
  resolve: {
    alias: {
      "@cleardeed/land-classifier": path.resolve(__dirname, "agents/land-classifier/index.ts"),
      "@cleardeed/fetcher-nominatim": path.resolve(__dirname, "packages/fetchers/nominatim/src/index.ts"),
      "@cleardeed/fetcher-bhunaksha": path.resolve(__dirname, "packages/fetchers/bhunaksha/src/index.ts"),
      "@cleardeed/fetcher-ecourts": path.resolve(__dirname, "packages/fetchers/ecourts/src/index.ts"),
      "@cleardeed/fetcher-bhulekh": path.resolve(__dirname, "packages/fetchers/bhulekh/src/index.ts"),
      "@cleardeed/fetcher-high-court": path.resolve(__dirname, "packages/fetchers/high-court/src/index.ts"),
      "@cleardeed/fetcher-drt": path.resolve(__dirname, "packages/fetchers/drt/src/index.ts"),
      "@cleardeed/fetcher-rccms": path.resolve(__dirname, "packages/fetchers/rccms/src/index.ts"),
      "@cleardeed/fetcher-igr-ec": path.resolve(__dirname, "packages/fetchers/igr-ec/src/index.ts"),
      "@cleardeed/schema": path.resolve(__dirname, "packages/schema/src/index.ts"),
      "@cleardeed/fetcher-cersai": path.resolve(__dirname, "packages/fetchers/cersai/src/index.ts"),
      "@cleardeed/fetcher-rera": path.resolve(__dirname, "packages/fetchers/rera/src/index.ts"),
      "@cleardeed/fetcher-larr": path.resolve(__dirname, "packages/fetchers/larr/src/index.ts"),
      "@cleardeed/orchestrator": path.resolve(__dirname, "packages/orchestrator/src/index.ts"),
      "@cleardeed/pdf-renderer": path.resolve(__dirname, "packages/pdf-renderer/src/index.ts"),
      "@cleardeed/consumer-report-writer": path.resolve(__dirname, "agents/consumer-report-writer/src/index.ts"),
      "@cleardeed/ownership-reasoner": path.resolve(__dirname, "agents/ownership-reasoner/index.ts"),
      "@cleardeed/encumbrance-reasoner": path.resolve(__dirname, "agents/encumbrance-reasoner/index.ts"),
    },
  },
});
