import { defineConfig } from "vitest/config";
import path from "path";

export default defineConfig({
  test: {
    environment: "node",
    testTimeout: 300_000,
    include: [
      "packages/captcha-breaker/src/**/*.test.ts",
      "packages/fetchers/nominatim/src/**/*.test.ts",
      "packages/fetchers/bhulekh/src/**/*.test.ts",
      "packages/fetchers/bhunaksha/src/**/*.test.ts",
      "packages/fetchers/bhunaksha-plot-report/src/**/*.test.ts",
      "packages/render/src/**/*.test.ts",
      "packages/fetchers/ecourts/src/**/*.test.ts",
      "packages/fetchers/high-court/src/**/*.test.ts",
      "packages/fetchers/drt/src/**/*.test.ts",
      "packages/fetchers/rccms/src/**/*.test.ts",
      "packages/fetchers/igr-ec/src/**/*.test.ts",
      "packages/fetchers/cersai/src/**/*.test.ts",
      "packages/fetchers/rera/src/**/*.test.ts",
      "packages/fetchers/larr/src/**/*.test.ts",
      "packages/fetchers/circle-rate/src/**/*.test.ts",
      "packages/fetchers/bda-zoning/src/**/*.test.ts",
      "packages/fetchers/igr-sro/src/**/*.test.ts",
      "packages/fetchers/igr-bmv/src/**/*.test.ts",
      "packages/fetchers/stamp-duty/src/**/*.test.ts",
      "packages/fetchers/igr-daily-bulletin/src/**/*.test.ts",
      "packages/fetchers/public-dashboard/src/**/*.test.ts",
      "packages/fetchers/govt-fee/src/**/*.test.ts",
      "packages/fetchers/igr-certified-copy/src/**/*.test.ts",
      "packages/fetchers/eow/src/**/*.test.ts",
      "packages/fetchers/bhuvan-flood/src/**/*.test.ts",
      "packages/schema/src/**/*.test.ts",
      "packages/orchestrator/src/**/*.test.ts",
      "agents/ownership-reasoner/**/*.test.ts",
      "agents/encumbrance-reasoner/**/*.test.ts",
      "agents/consumer-report-writer/src/**/*.test.ts",
      "apps/web/public/mapcard-v1.test.js",
      "agents/output-auditor/src/**/*.test.ts",
      "agents/land-classifier/**/*.test.ts",
      "packages/pdf-renderer/src/**/*.test.ts",
      "apps/web/src/lib/track.test.ts",
      "apps/web/src/lib/auth-helpers.test.ts",
      "apps/web/src/lib/supabase/middleware.test.ts",
      "apps/web/src/lib/villages.test.ts",
      "apps/web/src/lib/pipeline/pid/keys.test.ts",
      "apps/web/src/lib/pipeline/pid/mapper.test.ts",
      "apps/web/src/lib/pipeline/pid/types.test.ts",
      "apps/web/src/lib/pipeline/pid/client.test.ts",
      "apps/web/src/lib/pipeline/pid/record-fetch-result.test.ts",
      "apps/web/src/lib/pipeline/pid/build-pattern-payload.test.ts",
      "apps/web/src/lib/pipeline/pid/record-pattern-fires.test.ts",
      "apps/web/src/lib/pipeline/corpus.test.ts",
      "apps/web/src/lib/pipeline/contracts/fire.test.ts",
      "apps/web/src/lib/pipeline/contracts/fire.snapshot.test.ts",
      "apps/web/src/lib/pipeline/contracts/fire.wire.test.ts",
      "apps/web/src/lib/pipeline/contracts/contract-test-factory.test.ts",
      "apps/web/src/lib/db.expiry.test.ts",
      "apps/web/src/lib/db.v11.test.ts",
      "apps/web/src/lib/plot-diagram-storage.test.ts",
      "apps/web/src/lib/plot-diagram-step.test.ts",
      "apps/web/src/lib/plot-diagram-cache.test.ts",
      "apps/web/src/lib/survey.test.ts",
      "apps/web/src/lib/report-access.test.ts",
      "apps/web/src/lib/razorpay-config.test.ts",
      "apps/web/src/lib/rate-limit.test.ts",
      "apps/web/src/app/api/reports/[id]/refresh/route.test.ts",
      "apps/web/src/app/api/user/delete/route.test.ts",
      "apps/web/src/app/api/survey/[token]/route.test.ts",
      "apps/web/src/app/api/admin/dashboard/rerun/route.test.ts",
      "qa/fetcher_tests/**/*.test.ts",
      "qa/section_validators/**/*.test.ts",
      "qa/cross_source_validator.test.ts",
      "qa/degradation_matrix.test.ts",
      "qa/ground_truth_expansion.test.ts",
      "qa/cersai_captcha_accuracy.test.ts",
      "qa/ecourts_parser_harness.test.ts",
      "qa/all_fetchers_live_smoke.test.ts",
      "qa/invalid_input_gate.test.ts",
      "qa/auto-review-guardrails.test.ts",
      "qa/pid_smoke/**/*.test.ts",
      "qa/perf-baseline.test.mjs",
      "qa/load-test.test.mjs",
      "qa/funnel_dedup.test.ts",
      "qa/funnel_events.test.ts",
      "qa/docs.test.ts",
      "qa/launch-checklist.test.mjs",
    ],
  },
  resolve: {
    alias: {
      "@cleardeed/captcha-breaker": path.resolve(__dirname, "packages/captcha-breaker/src/index.ts"),
      "@/*": path.resolve(__dirname, "./apps/web/src/*"),
      "@/lib/db": path.resolve(__dirname, "./apps/web/src/lib/db"),
      "@/lib/auth-helpers": path.resolve(__dirname, "./apps/web/src/lib/auth-helpers"),
      "@/lib/supabase/server": path.resolve(__dirname, "./apps/web/src/lib/supabase/server"),
      "@/lib/supabase/browser": path.resolve(__dirname, "./apps/web/src/lib/supabase/browser"),
      "@/lib/report-access": path.resolve(__dirname, "./apps/web/src/lib/report-access"),
      "@/lib/track": path.resolve(__dirname, "./apps/web/src/lib/track"),
      "@/lib/email": path.resolve(__dirname, "./apps/web/src/lib/email"),
      "@/lib/payment": path.resolve(__dirname, "./apps/web/src/lib/payment"),
      "@/lib/pipeline": path.resolve(__dirname, "./apps/web/src/lib/pipeline/index"),
      "@/lib/pipeline/contracts": path.resolve(__dirname, "./apps/web/src/lib/pipeline/contracts/index"),
      "@cleardeed/land-classifier": path.resolve(__dirname, "agents/land-classifier/index.ts"),
      "@cleardeed/regulatory-screener": path.resolve(__dirname, "agents/regulatory-screener/index.ts"),
      "@cleardeed/fetcher-nominatim": path.resolve(__dirname, "packages/fetchers/nominatim/src/index.ts"),
      "@cleardeed/fetcher-bhunaksha": path.resolve(__dirname, "packages/fetchers/bhunaksha/src/index.ts"),
      "@cleardeed/fetcher-bhunaksha-plot-report": path.resolve(__dirname, "packages/fetchers/bhunaksha-plot-report/src/index.ts"),
      "@cleardeed/fetcher-ecourts": path.resolve(__dirname, "packages/fetchers/ecourts/src/index.ts"),
      "@cleardeed/fetcher-bhulekh": path.resolve(__dirname, "packages/fetchers/bhulekh/src/index.ts"),
      "@cleardeed/fetcher-high-court": path.resolve(__dirname, "packages/fetchers/high-court/src/index.ts"),
      "@cleardeed/fetcher-drt": path.resolve(__dirname, "packages/fetchers/drt/src/index.ts"),
      "@cleardeed/fetcher-rccms": path.resolve(__dirname, "packages/fetchers/rccms/src/index.ts"),
      "@cleardeed/fetcher-igr-ec": path.resolve(__dirname, "packages/fetchers/igr-ec/src/index.ts"),
      "@cleardeed/schema": path.resolve(__dirname, "packages/schema/src/index.ts"),
      "@cleardeed/fetcher-cersai": path.resolve(__dirname, "packages/fetchers/cersai/src/index.ts"),
      "@cleardeed/fetcher-rera": path.resolve(__dirname, "packages/fetchers/rera/src/index.ts"),
      "@cleardeed/fetcher-larr": path.resolve(__dirname, "packages/fetchers/larr/src/index.ts"),
      "@cleardeed/fetcher-circle-rate": path.resolve(__dirname, "packages/fetchers/circle-rate/src/index.ts"),
      "@cleardeed/fetcher-bda-zoning": path.resolve(__dirname, "packages/fetchers/bda-zoning/src/index.ts"),
      "@cleardeed/fetcher-igr-sro": path.resolve(__dirname, "packages/fetchers/igr-sro/src/index.ts"),
      "@cleardeed/fetcher-igr-bmv": path.resolve(__dirname, "packages/fetchers/igr-bmv/src/index.ts"),
      "@cleardeed/fetcher-stamp-duty": path.resolve(__dirname, "packages/fetchers/stamp-duty/src/index.ts"),
      "@cleardeed/fetcher-igr-daily-bulletin": path.resolve(__dirname, "packages/fetchers/igr-daily-bulletin/src/index.ts"),
      "@cleardeed/fetcher-public-dashboard": path.resolve(__dirname, "packages/fetchers/public-dashboard/src/index.ts"),
      "@cleardeed/fetcher-govt-fee": path.resolve(__dirname, "packages/fetchers/govt-fee/src/index.ts"),
      "@cleardeed/fetcher-igr-certified-copy": path.resolve(__dirname, "packages/fetchers/igr-certified-copy/src/index.ts"),
      "@cleardeed/fetcher-eow": path.resolve(__dirname, "packages/fetchers/eow/src/index.ts"),
      "@cleardeed/fetcher-bhuvan-flood": path.resolve(__dirname, "packages/fetchers/bhuvan-flood/src/index.ts"),
      "@cleardeed/orchestrator": path.resolve(__dirname, "packages/orchestrator/src/index.ts"),
      "@cleardeed/pdf-renderer": path.resolve(__dirname, "packages/pdf-renderer/src/index.ts"),
      "@cleardeed/consumer-report-writer": path.resolve(__dirname, "agents/consumer-report-writer/src/index.ts"),
      "@cleardeed/ownership-reasoner": path.resolve(__dirname, "agents/ownership-reasoner/index.ts"),
      "@cleardeed/encumbrance-reasoner": path.resolve(__dirname, "agents/encumbrance-reasoner/index.ts"),
      "@cleardeed/output-auditor": path.resolve(__dirname, "agents/output-auditor/src/index.ts"),
    },
  },
});
