-- ClearDeed — Plot diagram columns on reports
-- Migration: 016_plot_diagram_columns
-- Created: 2026-06-19
-- Phase 8 (Task 35) of the unified insight engine.
--
-- Adds three columns to the reports table to persist the plot diagram SVG
-- generated by the V1.1 pipeline:
--
--   plot_diagram_url           — public Supabase Storage URL (nullable)
--   plot_diagram_status        — "success" | "partial" | "failed" | "not_attempted"
--   plot_diagram_rendered_at   — ISO timestamp the SVG was last rendered
--
-- Nullable so the column can be added without backfilling existing reports
-- (Task 34 created the storage bucket; Task 35 wires the pipeline).

ALTER TABLE reports
  ADD COLUMN IF NOT EXISTS plot_diagram_url text,
  ADD COLUMN IF NOT EXISTS plot_diagram_status text,
  ADD COLUMN IF NOT EXISTS plot_diagram_rendered_at timestamptz;

COMMENT ON COLUMN reports.plot_diagram_url IS
  'Public Supabase Storage URL for the rendered plot diagram SVG (Phase 8 Task 35).';
COMMENT ON COLUMN reports.plot_diagram_status IS
  'Pipeline status for the plot diagram step: success | partial | failed | not_attempted (Task 35).';
COMMENT ON COLUMN reports.plot_diagram_rendered_at IS
  'ISO timestamp the SVG was last rendered / uploaded (Task 35).';

-- Index supports the 7-day cache lookup by rendered_at. Reports older than
-- the cache window are cheap to skip; we want the planner to scan recent
-- rows fast when checking whether a (gps + plot + village) report has a
-- cached diagram already.
CREATE INDEX IF NOT EXISTS idx_reports_plot_diagram_cache
  ON reports (plot_diagram_status, plot_diagram_rendered_at)
  WHERE plot_diagram_url IS NOT NULL;
