/**
 * Golden-path fixture — GPS 20.272688, 85.701271 (Mendhasala, Bhubaneswar)
 *
 * Known-correct inputs for A10 ConsumerReportWriter testing.
 * Owner on Bhulekh (Odia): କୃଷ୍ଣଚନ୍ଦ୍ର ବଡ଼ଯେନା (Krushnachandra Barajena)
 * Claimed owner (user input): Mohapatra
 * eCourts: manual-required zero-case output; no accepted-captcha confidence claim
 * Bhunaksha: plot #415, village Mendhasala, area ~0.308 km²
 */

import type { ConsumerReportInput } from "../schema";

export const CONSUMER_REPORT_FIXTURE: ConsumerReportInput = {
  reportId: "CLD-GOLDEN-001",
  generatedAt: "2026-04-20T10:30:00.000Z",

  // User-provided inputs
  gpsCoordinates: {
    latitude: 20.272688,
    longitude: 85.701271,
  },
  claimedOwnerName: "Mohapatra",
  plotDescription: "Plot in Mendhasala village, Bhubaneswar, Khordha district",

  // Tier 1 outputs (from orchestrator golden path)
  geoFetch: {
    village: "Chandaka",
    tahasil: "Bhubaneswar",
    district: "Khordha",
    state: "Odisha",
    postcode: "752054",
    displayName: "Chandaka, Bhubaneswar, Khordha, Odisha, 752054, India",
    gpsSource: "nominatim",
  },
  revenueRecords: {
    khataNo: "830",
    village: "Mendhasala",
    district: "Khordha",
    riCircle: "11",
    lastUpdated: "01-01-2018",
    tenants: [
      {
        tenantName: "କୃଷ୍ଣଚନ୍ଦ୍ର ବଡ଼ଯେନା",
        surveyNo: "309",
        area: 10.5,
        unit: "acre",
        landClass: "ଦଣ୍ଡା",
        fatherName: "ପ୍ରତିମା ଚନ୍ଦ୍ର ବଡ଼ଯେନା",
      },
      {
        tenantName: "ପ୍ରତିମା ଚନ୍ଦ୍ର ବଡ଼ଯେନା",
        surveyNo: "309",
        area: 10.5,
        unit: "acre",
        landClass: "ଦଣ୍ଡା",
      },
      {
        tenantName: "ସୁବ୍ର ଚନ୍ଦ୍ର ବଡ଼ଯେନା",
        surveyNo: "309",
        area: 10.5,
        unit: "acre",
        landClass: "ଦଣ୍ଡା",
      },
      {
        tenantName: "ଗୌର ଚନ୍ଦ୍ର ବଡ଼ଯେନା",
        surveyNo: "309",
        area: 10.5,
        unit: "acre",
        landClass: "ଦଣ୍ଡା",
      },
      {
        tenantName: "ସୁନୀତା ଦେବୀ",
        surveyNo: "309",
        area: 10.5,
        unit: "acre",
        landClass: "ଦଣ୍ଡା",
      },
    ],
  },
  courtCases: {
    total: 0,
    cases: [],
  },
  registryLinks: {
    url: "https://igrodisha.gov.in/ecsearch",
    params: {
      district: "Khordha",
      sro: "Not verified",
      plotNo: "415",
      ownerName: "Krushnachandra Barajena",
    },
    instructions:
      "Visit igrodisha.gov.in, select the current district/SRO in the live IGR flow, search by plot number 415 or owner name, and obtain the EC for lawyer review.",
  },

  // Tier 2 outputs (will be generated by A5–A8 in production)
  ownershipReasoner: {
    officialOwnerName: "କୃଷ୍ଣଚନ୍ଦ୍ର ବଡ଼ଯେନା (Krushnachandra Barajena)",
    transliteratedOwnerName: "Krushnachandra Barajena",
    nameMatch: "partial", // Mohapatra ≠ Barajena — surname mismatch, partial match not applicable
    nameMatchConfidence: { score: 0.1, method: "surname_comparison" },
    discrepancyExplanation:
      "The official Bhulekh record shows the owner as 'Krushnachandra Barajena' (Odia: କୃଷ୍ଣଚନ୍ଦ୍ର ବଡ଼ଯେନା), which does not match the seller-claimed name 'Mohapatra'. This is a significant discrepancy — the Bhulekh record may relate to a different person, or the plot may have changed hands without mutation. Ask the seller to explain this difference and produce documents linking Mohapatra to this plot.",
    coOwners: [
      "Pratima Chandra Barajena",
      "Subhra Chandra Barajena",
      "Gaur Chandra Barajena",
      "Sunita Debi",
    ],
    fatherNameOnRecord: "Pratima Chandra Barajena",
    confidence: 0.3,
    confidenceBasis:
      "Bhulekh returned RoR but claimed owner 'Mohapatra' does not match any Bhulekh tenant name. Confidence low.",
  },
  landClassifier: {
    currentClassification: "Agricultural — irrigated (ଦଣ୍ଡା)",
    classificationSource: "Bhulekh land class field (lbllType per plot)",
    permittedUses: ["Agriculture only without conversion"],
    conversionRequired: true,
    conversionSteps:
      "Land use conversion may be required from agricultural to residential/commercial. Confirm the current process and timeline with the Odisha Revenue Department or tehsil office.",
    redFlags: [
      {
        flag: "Conversion Required",
        severity: "medium",
        description:
          "This land is classified as agricultural (irrigated) in the source fixture. Converting it to residential or commercial use requires prior approval from the Odisha Revenue Department; confirm the current process and timeline with the tehsil office or a property lawyer.",
        recommendedAction:
          "Ask the seller whether they intend to convert this land to your intended use. Confirm if conversion has been initiated or is pending.",
      },
      {
        flag: "Multiple Owners",
        severity: "medium",
        description:
          "The Bhulekh record shows 5 co-owners for this plot (Krushnachandra Barajena, Pratima Chandra Barajena, Subhra Chandra Barajena, Gaur Chandra Barajena, Sunita Debi). All co-owners must consent to any sale or transfer.",
        recommendedAction:
          "Ask the seller to confirm all co-owners are aware of and consent to this sale. If any co-owner is outside Odisha or deceased, additional documentation may be required.",
      },
    ],
    confidence: 0.85,
    confidenceBasis: "Bhulekh RoR returned with land class and 5 tenant records.",
  },
  encumbranceReasoner: {
    status: "manual_required",
    instructions:
      "The Encumbrance Certificate (EC) must be obtained manually from IGR Odisha. Visit igrodisha.gov.in, select the current district/SRO in the live IGR flow, search by plot number 415 or the owner's name, and obtain the EC for lawyer review. Alternatively, visit the Sub-Registrar office in person.",
    confidence: 0.0,
    confidenceBasis: "EC retrieval is not automated in V1. Manual retrieval required.",
  },
  regulatoryScreener: {
    flags: [],
    plotConfirmedInRegulatedZone: false,
    overlaySource: "Bhunaksha GeoServer WFS (mapserver.odisha4kgeo.in)",
    confidence: 0.6,
    confidenceBasis:
      "Regulatory overlays were not checked in this fixture; manual verification is required for forest, PESA, CRZ, airport, archaeological, and town-planning restrictions.",
  },

  // Validation findings
  validationFindings: [
    {
      dimension: "village",
      severity: "warning",
      source: "orchestrator",
      description:
        'Village mismatch: Nominatim returns "Chandaka" but Bhunaksha returns "Mendhasala". Nominatim coverage in rural Odisha is coarse — Bhunaksha village is more reliable for plot identification.',
      raw: { nominatimVillage: "Chandaka", bhunakshaVillage: "Mendhasala" },
    },
    {
      dimension: "area",
      severity: "warning",
      source: "orchestrator",
      description:
        "Area discrepancy: Bhunaksha reports 0.3079 km² (~76 acres) vs Bhulekh total 52.5 acres (5 plots × 10.5 acres). Manual verification recommended — area mismatch may indicate duplicate records.",
      raw: { bhunakshaSqKm: 0.3079, bhulekhAcres: 52.5, reconcile: { pct: 52, tier: "warning" } },
    },
  ],

  disclaimerText: `This report is prepared by ClearDeed using publicly available government land records. It is not a legal opinion, not a title certificate, and not a guarantee of ownership or freedom from encumbrance. Before you transact: share this report with a qualified property lawyer, request original title documents from the seller going back at least 30 years, obtain an Encumbrance Certificate from the Sub-Registrar office, verify plot boundaries on the ground with a local survey, confirm land classification permits your intended use, and confirm no conversion of land use is required.`,
};

/**
 * Consumer report that SHOULD be produced from this fixture.
 * Expected key findings:
 * - Plot: located in Mendhasala, GPS confirmed
 * - Owner: NAME MISMATCH — seller says Mohapatra, Bhulekh says Krushnachandra Barajena
 * - Classification: agricultural (irrigated) in fixture; conversion status requires tehsil/lawyer confirmation
 * - Court cases: manual-required zero-case output
 * - Encumbrance: manual retrieval required
 * - What to ask next: 5 specific questions
 */
