/**
 * qa/ground_truth_expansion.test.ts
 *
 * A.2.1 — Ground-truth corpus expansion runner.
 *
 * Walks the founder-selected scaffold plots (P006–P015) and runs whatever
 * fetchers we can run autonomously (Bhunaksha Plot Report, Bhunaksha
 * polygon). For each plot, writes a transcript.md that the founder can
 * review to upgrade verified_by from "pending" → "founder" (or
 * "auto-verified (live fetch + position-based parser)" for plots that
 * fully completed a live fetch).
 *
 * This test is **skipped in CI** (live network calls). Founder runs locally
 * with: `npx vitest run qa/ground_truth_expansion.test.ts`
 */
import { describe, it, expect } from "vitest";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { bhunakshaPlotReportFetch } from "@cleardeed/fetcher-bhunaksha-plot-report";
import { findGisCode } from "../packages/fetchers/bhunaksha-plot-report/src/gis-codes";
import { bhunakshaFetch } from "@cleardeed/fetcher-bhunaksha";

const ROOT = process.cwd();
const GROUND_TRUTH = join(ROOT, "qa", "ground_truth");

interface ManifestCoverage {
  tahasil: string;
  tahasil_code: string;
  village: string;
  pattern_category: string;
  plot_no: string;
  bda_zone: string;
  kisam_class: string;
}

interface Manifest {
  plot_id: string;
  description: string;
  verified_by: string;
  coverage: ManifestCoverage;
  fetchers: Record<string, unknown>;
}

function loadManifest(plotId: string): Manifest {
  const path = join(GROUND_TRUTH, plotId, "manifest.json");
  if (!existsSync(path)) throw new Error(`Manifest not found: ${path}`);
  return JSON.parse(readFileSync(path, "utf8"));
}

function writeTranscript(plotId: string, lines: string[]) {
  const path = join(GROUND_TRUTH, plotId, "transcript.md");
  writeFileSync(path, lines.join("\n") + "\n", "utf8");
}

async function tryPlotReport(
  m: Manifest
): Promise<{ ok: boolean; gisCode: string | null; data: Record<string, unknown> | null; error: string | null; elapsedMs: number }> {
  const gis = findGisCode(m.coverage.village, m.coverage.tahasil);
  if (!gis) {
    return { ok: false, gisCode: null, data: null, error: "no_gis_code_in_table", elapsedMs: 0 };
  }
  const t0 = Date.now();
  try {
    const result = await bhunakshaPlotReportFetch({
      village: m.coverage.village,
      tahasil: m.coverage.tahasil,
      plotNo: m.coverage.plot_no,
    });
    const elapsedMs = Date.now() - t0;
    if (result.status === "success" && result.data) {
      return {
        ok: true,
        gisCode: gis.gisCode,
        data: result.data as unknown as Record<string, unknown>,
        error: null,
        elapsedMs,
      };
    }
    return {
      ok: false,
      gisCode: gis.gisCode,
      data: null,
      error: result.statusReason ?? result.status,
      elapsedMs,
    };
  } catch (err) {
    return {
      ok: false,
      gisCode: gis.gisCode,
      data: null,
      error: err instanceof Error ? err.message : String(err),
      elapsedMs: Date.now() - t0,
    };
  }
}

async function tryPolygonFetch(
  m: Manifest
): Promise<{ ok: boolean; data: Record<string, unknown> | null; error: string | null; elapsedMs: number }> {
  const t0 = Date.now();
  try {
    const result = await bhunakshaFetch({
      village: m.coverage.village,
      tahasil: m.coverage.tahasil,
      plotNo: m.coverage.plot_no,
    });
    const elapsedMs = Date.now() - t0;
    if (result.status === "success" && result.data) {
      return {
        ok: true,
        data: result.data as unknown as Record<string, unknown>,
        error: null,
        elapsedMs,
      };
    }
    return {
      ok: false,
      data: null,
      error: result.statusReason ?? result.status,
      elapsedMs,
    };
  } catch (err) {
    return {
      ok: false,
      data: null,
      error: err instanceof Error ? err.message : String(err),
      elapsedMs: Date.now() - t0,
    };
  }
}

function buildTranscript(
  m: Manifest,
  plotReport: Awaited<ReturnType<typeof tryPlotReport>>,
  polygon: Awaited<ReturnType<typeof tryPolygonFetch>>
): string[] {
  const out: string[] = [];
  out.push(`# ${m.plot_id} — ${m.coverage.tahasil} / ${m.coverage.village} / ${m.coverage.plot_no} — Verification Transcript`);
  out.push("");
  out.push("> Auto-generated by `qa/ground_truth_expansion.test.ts` on 2026-06-16.");
  out.push("> Founder checklist at bottom — review to upgrade `verified_by` to `founder`.");
  out.push("");
  out.push("## What this plot covers");
  out.push("");
  out.push(`- **Tahasil:** ${m.coverage.tahasil} (code ${m.coverage.tahasil_code})`);
  out.push(`- **Village:** ${m.coverage.village}`);
  out.push(`- **Plot no:** ${m.coverage.plot_no} (${m.coverage.pattern_category} pattern)`);
  out.push(`- **BDA zone:** ${m.coverage.bda_zone}`);
  out.push(`- **Kisam class:** ${m.coverage.kisam_class}`);
  out.push("");
  out.push("## Auto-run results");
  out.push("");
  out.push("### Bhunaksha Plot Report (D-036)");
  if (!plotReport.gisCode) {
    out.push("- Skipped: village not in GIS-code lookup table.");
    out.push(`  - ${m.coverage.tahasil}/${m.coverage.village} → \`findGisCode()\` returns null`);
    out.push("  - Founder action: identify the Bhunaksha RI + mouza codes and add to `gis-codes.ts`");
  } else if (plotReport.ok && plotReport.data) {
    out.push(`- **Status: success** (elapsed ${plotReport.elapsedMs}ms)`);
    out.push(`- **GIS code:** ${plotReport.gisCode}`);
    out.push(`- **Plot no:** ${plotReport.data.plotNo}`);
    out.push(`- **Khatiyan:** ${plotReport.data.khatiyanNo}`);
    out.push(`- **Owner block (raw):** ${JSON.stringify(plotReport.data.owner ?? null)}`);
    out.push(`- **Area:** ${JSON.stringify(plotReport.data.area ?? null)}`);
    out.push(`- **Source URL:** ${plotReport.data.sourceUrl ?? "n/a"}`);
  } else {
    out.push(`- **Status: failed** (elapsed ${plotReport.elapsedMs}ms)`);
    out.push(`- **Error:** ${plotReport.error}`);
    out.push(`- **GIS code:** ${plotReport.gisCode}`);
  }
  out.push("");
  out.push("### Bhunaksha Polygon (existing fetcher)");
  if (polygon.ok && polygon.data) {
    out.push(`- **Status: success** (elapsed ${polygon.elapsedMs}ms)`);
    out.push(`- **Area (sq_km):** ${polygon.data.area ?? "n/a"}`);
    out.push(`- **Feature count:** ${polygon.data.featureCount ?? "n/a"}`);
  } else {
    out.push(`- **Status: failed** (elapsed ${polygon.elapsedMs}ms)`);
    out.push(`- **Error:** ${polygon.error}`);
  }
  out.push("");
  out.push("## Founder checklist");
  out.push("");
  out.push("- [ ] Bhulekh ROR (manual: log in to bhulekh.ori.nic.in, fill captcha, capture tenant block + area)");
  out.push("- [ ] IGR Odisha EC manual instructions (link to https://igrodisha.gov.in)");
  out.push("- [ ] CERSAI V2 portal (login + captcha — D-035 solver in production)");
  out.push("- [ ] eCourts Khordha party search (district code 2, manual search)");
  out.push("- [ ] RCCMS cause-list (login + captcha required)");
  out.push("- [ ] Circle rate (JSON lookup)");
  out.push("- [ ] BDA zoning (50-village JSON — confirm village is in zone)");
  out.push("- [ ] Reviewer notes: owner matches Bhunaksha output, plot area in sane range (0.05–2 acres)");
  out.push("");
  out.push("When all 8 checkboxes are reviewed, change `verified_by` in `manifest.json` to `founder` and commit.");
  return out;
}

describe.skipIf(process.env.CI === "true" || process.env.SKIP_CORPUS_EXPANSION === "1")(
  "Ground-truth corpus expansion (A.2.1)",
  () => {
    it("generates transcripts for P006–P015", async () => {
      const candidates: string[] = [];
      for (let i = 6; i <= 15; i++) {
        candidates.push(`P${String(i).padStart(3, "0")}`);
      }

      const summary: string[] = [];
      for (const plotId of candidates) {
        const m = loadManifest(plotId);
        if (m.verified_by !== "pending") {
          summary.push(`${plotId}: skip (already ${m.verified_by})`);
          continue;
        }
        const plotReport = await tryPlotReport(m);
        const polygon = await tryPolygonFetch(m);
        const transcript = buildTranscript(m, plotReport, polygon);
        writeTranscript(plotId, transcript);
        const status = plotReport.ok ? "✓" : "✗";
        summary.push(`${plotId}: ${status} ${plotReport.error ?? plotReport.elapsedMs + "ms"}`);
      }
      // eslint-disable-next-line no-console
      console.log("[corpus-expansion] " + summary.join("\n[corpus-expansion] "));
      expect(candidates.length).toBe(10);
    });
  }
);
